Web/Controllers/SMSController.cs
using Web.Models;
using System;
using System.Threading.Tasks;
using System.Web.Mvc;
using System.Web.Security;
using Web.Application;
using API.Utilities;
using Web.Interfaces;
using Web.Codes;
using API.Models;
using System.Linq;
using Web.Extensions;
using Web.Attributes;
using Web.Codes.Constants;

namespace Web.Controllers
{
    public class SMSController : Controller
    {
        [CustomAuthorizeAttribute(OperationKey = "/SMS")]
        public ActionResult Index()
        {
            SMSModel model = new SMSModel();
            try
            {
                using (MyDbContext _db = new MyDbContext())
                {
                    model.SMSItems = _db.SMSLogs//.Where(a => !a.Deleted)
                                       .Select(a => new SMSItem
                                       {
                                           Id = a.Id,
                                           ActivityDate = a.ActivityDate,
                                           Message = a.Message,
                                           Recipient = a.Recipient,
                                           Status = a.Status,
                                           UnitsUsed = a.UnitsUsed,
                                       })
                                       .OrderBy(a => a.Id)
                                       .ToList();

                }
            }
            catch (Exception ex)
            {
                General.LogExceptions("", ex);
                ViewBag.MessageText = ex.Message.ToString();
                ViewBag.MessageType = MessageLabelControl.MessageType.danger;
            }
            return View(model);
        }

        [CustomAuthorizeAttribute(OperationKey = "/SMS/SendSMS")]
        public ActionResult SendSMS()
        {
            SMSModel model = new SMSModel();
            try
            {
                using (MyDbContext _db = new MyDbContext())
                {
                    model.SMSCategoryItems = _db.SMSContactCategorys//.Where(a => !a.Deleted)
                                       .Select(a => new SMSCategoryItem
                                       {
                                           Id = a.Id,
                                            CategoryName = a.CategoryName,
                                       })
                                       .OrderBy(a => a.Id)
                                       .ToList();

                }
            }
            catch (Exception ex)
            {
                General.LogExceptions("", ex);
                ViewBag.MessageText = ex.Message.ToString();
                ViewBag.MessageType = MessageLabelControl.MessageType.danger;
            }
            return View(model);
        }
    }
}

Web/Views/SMS/Index.cshtml
@model  Web.Models.SMSModel
@{
    ViewBag.Title = "SMS Manager";
}
<style type="text/css">

    .rcorners3 {
        border-radius: 25px;
    }
</style>
@using (Html.BeginForm("Index", "SMS", FormMethod.Post, new { id = "formSMS" }))
{
    <section class="content">
        <div class="row">
            <div class="col-xl-8 col-lg-7">
                <div class="row">
                    <div class="col-12">
                        <div class="box box-solid bg-dark">
                            <div class="box-header with-border">
                                <h3 class="box-title">All SMS</h3>
                                <h6 class="box-subtitle">Sent out SMS are listed here, you can manage them from here. You can export to Copy, CSV, Excel, PDF & Print</h6>
                            </div>
                            <div class="box-body">
                                <div class="table-responsive">
                                    <table id="example" class="table table-bordered table-hover display nowrap margin-top-10 w-p100">
                                        <thead>
                                            <tr>
                                                <th>Message</th>
                                                <th>Recipients</th>
                                                <th>Units&nbsp;Used</th>
                                                <th>Status</th>
                                                <th>Activity&nbsp;Date</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach (var item in Model.SMSItems)
                                            {
                                                <tr>
                                                    <td><a href="javascript:;" data-id="@item.Id" class="view-butto">@item.Message</a></td>
                                                    <td>@item.Recipient</td>
                                                    <td>@item.UnitsUsed</td>
                                                    <td>@item.Status</td>
                                                    <td>@item.ActivityDate</td>
                                                </tr>
                                            }
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xl-4 col-lg-5">
                <!-- Profile Image -->
                <div class="box bg-info bg-deathstar-dark">
                    <div class="box-body box-profile">
                        <h2 class="profile-username text-center mb-0">SMS Account Balanace and Details</h2>
                        <div class="box-body">
                            <div class="form-group">
                                <label class="mr-25">SMS Units Used</label>
                                <div class="input-group">
                                    <span id="sms-units-used"></span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>


    <div class="modal fade text-left" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel17"
         aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="modal-header-text">Create a Contact Category</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label for="BusinessName">Enter Category Name</label>
                                <input type="text" id="CategoryName" class="form-control" />
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn grey btn-outline-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-outline-primary">Save changes</button>
                </div>
            </div>
        </div>
    </div>
}


<script src="~/assets/vendor_components/jquery/dist/jquery.js"></script>
<script type="text/javascript">
    $(document).ready(function () {

       

        $("#formSMS").submit(function (e) {
            e.preventDefault();
            swal.fire({
                title: 'Create Category?',
                showCancelButton: true,
                confirmButtonText: 'Yes, Create',
                showLoaderOnConfirm: true,
                preConfirm: function () {
                    return new Promise(function (resolve) {
                        setTimeout(function () {
                            resolve();
                        }, 2000);
                    });
                },
                allowOutsideClick: false
            }).then(function () {

                $.ajax({
                    type: "POST",
                    url: "/api/SMS/create-category",
                    data: {
                        'CategoryName': $('#CategoryName').val(),
                    },
                    cache: false,
                    success: function (resp) {
                        if (resp.ResponseCode !== null && resp.ResponseCode === '00') {
                            swal.fire(
                                "Success!",
                                resp.ResponseMsg,
                                "success"
                            ).then(function () {
                                window.location.replace("../SMS/");
                            });
                        }
                        if (resp.ResponseCode !== null && resp.ResponseCode === '96') {
                            swal.fire(
                                "Error Occured!",
                                resp.ResponseMsg,
                                "warning"
                            );
                        }
                    },
                    failure: function (resp) {
                        swal.fire(
                            "Internal Error",
                            "Oops, Error Occurred.",
                            "error"
                        );
                    }
                });
            });
        });

        $("#ResetButton").click(function () {
            alert("You are about to reset the Database AFRESH.");
            $.ajax({
                type: "GET",
                url: "/Dashboard/ResetDemo",
                data: '',
                contentType: "application/json; charset=utf-8",
                async: true,
                success: function (resp) {
                    if (resp.ResponseCode !== null && resp.ResponseCode === '00') {
                        swal.fire(
                            "Success!",
                            resp.ResponseMsg,
                            "success"
                        ).then(function () {
                            window.location.replace("../Dashboard/");
                        });
                    }
                    if (resp.ResponseCode !== null && resp.ResponseCode === '96') {
                        swal.fire(
                            "Error Occured!",
                            resp.ResponseMsg,
                            "warning"
                        );
                    }
                }
            });
        });

        $('#dtable').find('.app-details').each(function (e) {
            $(this).click(function (e) {
                e.preventDefault();
                var _id = $(this).data('id');
                var url = '../Applications/AllApplicationDetails?' + _id;
                window.open(url, '_blank');
            });
        });

        $('#dtable').find('.app-history').each(function (e) {
            $(this).click(function (e) {
                e.preventDefault();
                var _id = $(this).data('id');
                var url = '../Applications/AllApplicationHistory?' + _id;
                window.open(url, '_blank');
            });
        });

        $('#dtable').find('.edit-button').each(function () {
            $(this).click(function (e) {
                e.preventDefault();
                var _id = $(this).data('id');
                $.ajax({
                    type: "GET",
                    url: "/api/br_api/fetchAppForm?Id=" + _id,
                    contentType: "application/json; charset=utf-8",
                    async: true,
                    success: function (response) {
                        if (response.ComplaintName !== null && response.ComplaintName !== '') {
                            $('#UserID').text(response.UserID);
                            $('#ApplicationNumber').text(response.ApplicationNumber);
                            $('#Email').text(response.Email);
                            $('#PhoneNumber').text(response.PhoneNumber);
                            $('#Country').text(response.Country);
                            $('#TransactionStatus').text(response.ApplicationStatus);
                            $('#TransactionType').text(response.TransactionType);
                            $('#TransactionAmount').text(response.TransactionAmount);
                        }
                        else {
                            var msg = 'Error Occurred.<br/>';
                            alert(msg += response.ResponseMsg);
                        }
                    },
                    error: function (XMLHttpRequest, textStatus, errorThrown) {
                    }
                }).done(function () {

                });
            });
        });

        $('#dtable').find('.app-delete').each(function () {
            $(this).click(function (e) {
                e.preventDefault();
                var _id = $(this).data('id');
                var request = {
                    'ApplicationNumber': _id
                };
                var _data = JSON.stringify(request);
                Swal.fire({
                    title: 'Are you sure?',
                    text: 'You want to delete this Application!',
                    icon: 'warning',
                    showCancelButton: true,
                    confirmButtonText: 'Yes, delete it!',
                    cancelButtonText: 'No, dont'
                }).then((result) => {
                    if (result.value) {
                        $.ajax({
                            type: "POST",
                            url: "/api/br_api/del-app",
                            contentType: "application/json; charset=utf-8",
                            data: _data,
                            cache: false,
                            success: function (resp) {
                                if (resp.ResponseCode !== null && resp.ResponseCode === '00') {
                                    swal.fire(
                                        "Success!",
                                        resp.ResponseMsg,
                                        "success"
                                    ).then(function () {
                                        location.reload();
                                    });
                                }
                                if (resp.ResponseCode !== null && resp.ResponseCode === '96') {
                                    swal.fire(
                                        "Warning!",
                                        resp.ResponseMsg,
                                        "warning"
                                    )
                                }
                            },
                            failure: function (resp) {
                                swal.fire(
                                    "Internal Error",
                                    "Oops, Error Occurred.",
                                    "error"
                                )
                            }
                        });
                    } else if (result.dismiss === Swal.DismissReason.cancel) {
                        Swal.fire(
                            'Cancelled',
                            'You have cancelled your request',
                            'error'
                        )
                    }
                })
            });
        });



    });
</script>

<style type="text/css">

    .rcorners3 {
        border-radius: 25px;
    }
</style>

Web/Views/SMS/SendSMS.cshtml
@model  Web.Models.SMSModel
@{
    ViewBag.Title = "Send SMS";
}

@section breadcrumb {
    <li class="breadcrumb-item active" aria-current="page">Send SMS</li>
}
<section class="content">
    <div class="row">
        <div class="col-lg-6 col-12">
            <div class="box">
                <div class="box-header with-border">
                    <h4 class="box-title">Manual Repayment</h4>
                    <div class="box-controls pull-right">
                    </div>
                </div>
                <form id="formSendMessage">
                    <div class="box-body">
                        <div class="form-group">
                            <label class="mr-25">Select From your Category List</label>
                            <div class="input-group">
                                <select id="CategoryList" required="required" class="form-control">
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="mr-25">Reciepients</label>
                            <div class="input-group">
                                <textarea rows="6" id="Reciepients" class="form-control"></textarea>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="row">
                                <div class="col-12">
                                    <label class="mr-25">Enter Message</label>
                                    <div class="input-group">
                                        <textarea rows="6" id="Message" class="form-control"></textarea>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <button type="submit" class="btn btn-success btn-lg btn-block">Send Message</button>
                    </div>
                </form>
            </div>
        </div>


        <div class="col-lg-6 col-12">
            <div class="box">
                <div class="box-header with-border">
                    <h4 class="box-title">SMS Reciepients</h4>
                    <div class="box-controls pull-right">
                    </div>
                </div>
                <div class="box-body">
                    <div class="table-responsive">
                        <table id="example" class="table table-bordered table-hover display nowrap margin-top-10 w-p100">
                            <thead>
                                <tr>
                                    <th>Categories</th>
                                    <th>Add&nbsp;Reciepient</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model.SMSCategoryItems)
                                {
                                <tr>
                                    <td><a href="javascript:;">@item.CategoryName</a></td>
                                    <td><a data-id="@item.Id" href="javascript:;" class="add-reciepient btn btn-sm btn-purple" data-toggle="modal" data-target="#myModal">Repay&nbsp;Loan</a></td>
                                </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>


<div class="modal fade text-left" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel17"
     aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="modal-header-text"></h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form id="AddNewReciepient">
                    <div class="box-body">
                        <div class="form-group">
                            <label class="mr-25">Reciepients</label>
                            <div class="input-group">
                                <textarea rows="6" id="Reciepients" class="form-control"></textarea>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="mr-25">Reciepients Name</label>
                            <div class="input-group">
                                <input type="text" id="ReciepientsName" class="form-control" />
                            </div>
                        </div>
                        <button type="submit" class="btn btn-success btn-lg btn-block">Send Message</button>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn grey btn-outline-secondary" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-outline-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>

<script src="~/assets/vendor_components/jquery/dist/jquery.js"></script>
<script type="text/javascript">
    $(document).ready(function () {

        $('#example').find('.add-reciepient').each(function () {
            $(this).click(function (e) {
                e.preventDefault();
                var _id = $(this).data('id');
                $.ajax({
                    type: "GET",
                    url: "/api/SMS/fetch?Id=" + _id,
                    contentType: "application/json; charset=utf-8",
                    async: true,
                    success: function (response) {
                        if (response.Reciepients != null && response.Reciepients != '') {                           
                            $('#Reciepients').val(response.PhoneNumber);
                            $("#SaveButton").show();
                            $('#modal-header-text').text('Add SMS Reciepients for ' + response.Categoryname);
                            $('#myModal').modal({
                                'backdrop': 'static',
                                "keyboard": false,
                                "show": true
                            });
                        }
                        else {
                            swal.fire(
                                "Internal Error",
                                response.ResponseMsg,
                                "error"
                            );
                        }
                    },
                    error: function (XMLHttpRequest, textStatus, errorThrown) {
                        swal.fire(
                            "Internal Error",
                            response.ResponseMsg,
                            "error"
                        );
                    }
                }).done(function () {

                });
            });
        });

        $.ajax({
            type: "GET",
            url: "/api/loan/fetchUsersLoan",
            data: "{}",
            async: true,
            success: function (data) {
                var s = '<option value="">Please choose a Loan Type</option>';
                for (var i = 0; i < data.length; i++) {
                    var amount = formatter.format(data[i].LoanAmount);
                    s += '<option value="' + data[i].LoanApplicationNumber + '">Loan Application Number : ' + data[i].LoanApplicationNumber + '(Amount : ' + amount + ')</option>';

                }
                $("#LoanType").html(s);
                $("#LoanType_online").html(s);
                $("#LoanType_online").html(s);
            }
        });


        $("#LoanType").change(function () {
            var _id = this.value;

            $.ajax({
                type: "GET",
                url: "/api/loan/fetchLoanDetails?Id=" + _id,
                contentType: "application/json; charset=utf-8",
                async: true,
                success: function (response) {
                    console.log(response);
                    if (response.UserID !== null && response.UserID !== '') {
                        var LoanBal = formatter.format(response.BalanceRecieved);
                        $("#BalanceRecieved").val(LoanBal);
                        var LoanBalRem = formatter.format(response.BalanceRemaining);
                        $("#BalanceRemaining").val(LoanBalRem);
                        $("#LoanRepaid").val(response.AppStatus);
                        $("#LoanStatus").val(response.LoanStatus);
                        $("#LastComment").val(response.Comment);
                        $("#hdnBalanceRemaining").val(response.BalanceRemaining);
                        $("#LoanApplied").val(response.MonthYear);
                        $("#LoanNextPayment").val(response.LoanNextPayment);
                        $("#hdnLoanAmount").val(response.LoanAmount);
                    }
                    else {
                        swal.fire(
                            "Error occurred!",
                            response.ResponseMsg,
                            "warning"
                        )
                    }
                },
                error: function (XMLHttpRequest, textStatus, errorThrown) {
                }
            }).done(function () {

            });

        });

        $("#AddNewReciepient").submit(function (e) {
            e.preventDefault();
            swal.fire({
                title: 'Add New Reciepient?',
                showCancelButton: true,
                confirmButtonText: 'Yes, Add',
                showLoaderOnConfirm: true,
                preConfirm: function () {
                    return new Promise(function (resolve) {
                        setTimeout(function () {
                            resolve();
                        }, 2000);
                    });
                },
                allowOutsideClick: false
            }).then(function () {

                $.ajax({
                    type: "POST",
                    url: "/api/SMS/addReciepient",
                    data: {
                        'BalanceRemaining': $('#hdnBalanceRemaining').val(),
                        'LoanApplicationNumber': $("#LoanType option:selected").val(),
                        'CustomerEmail': $('#CustomerEmail').val(),
                        'AmountPaid': $('#AmountPaid').val(),
                        'LoanStatus': $('#LoanStatus').val(),
                        'Month': $('#RepaymentMonth option:selected').val(),
                        'Year': $('#RepaymentYear option:selected').val(),
                        'LoanAmount': $('#hdnLoanAmount').val()
                    },
                    cache: false,
                    success: function (resp) {
                        if (resp.ResponseCode !== null && resp.ResponseCode === '00') {
                            swal.fire(
                                "Success!",
                                resp.ResponseMsg,
                                "success"
                            ).then(function () {
                                window.location.replace("../LoanManager/Repay");
                            });
                        }
                        if (resp.ResponseCode !== null && resp.ResponseCode === '96') {
                            swal.fire(
                                "Error Occured!",
                                resp.ResponseMsg,
                                "error"
                            );
                        }
                    },
                    failure: function (resp) {
                        swal.fire(
                            "Internal Error",
                            "Oops, Error Occurred.",
                            "error"
                        );
                    }
                });
            });
        });

    });
</script>